const EMPTY = [];

const SMALL = [
  {
    id: "1",
    imageSource: "/images/menu1.png",
    title: "T398",
    price: 5.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/menu2.png",
    title: "C236",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const LARGE = [
  {
    id: "1",
    imageSource: "/images/menu1.png",
    title: "Fresh Mix",
    price: 5.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/menu7.png",
    title: "Sushi Mix",
    price: 12.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },

  {
    id: "3",
    imageSource: "/images/menu5.png",
    title: "California Star",
    price: 4.167,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/menu9.png",
    title: "Just Salmon",
    price: 5.4985,
    quantity: 0,
    isAvailable: false,
    isAdvertised: true,
  },

  {
    id: "5",
    imageSource: "/images/menu3.png",
    title: "Super Salmon",
    price: 4.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/images/menu13.png",
    title: "Sunrise",
    price: 3.356,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/images/menu14.png",
    title: "California Dream",
    price: 4.567,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "8",
    imageSource: "/images/menu12.png",
    title: "Amateur Mix",
    price: 4.1678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/images/menu11.png",
    title: "Crazee Box",
    price: 3.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/images/menu2.png",
    title: "Sunset",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "11",
    imageSource: "/images/menu16.png",
    title: "Veggie Box",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "12",
    imageSource: "/images/menu15.png",
    title: "Tasty Box",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
];

export const fakeMenu = {
  EMPTY,
  SMALL,
  LARGE,
};
