const EMPTY = [];

const SMALL = [
  {
    id: "1",
    imageSource: "/images/menu1.png",
    title: "T398",
    price: 5.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/menu2.png",
    title: "C236",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const LARGE = [
  {
    id: "1",
    imageSource: "/images/menu1.png",
    title: "B555",
    price: 5.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/menu7.png",
    title: "B354",
    price: 12.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },

  {
    id: "3",
    imageSource: "/images/menu5.png",
    title: "C345",
    price: 4.167,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/menu9.png",
    title: "V156",
    price: 5.4985,
    quantity: 0,
    isAvailable: false,
    isAdvertised: true,
  },

  {
    id: "5",
    imageSource: "/images/menu3.png",
    title: "G345",
    price: 4.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/images/menu13.png",
    title: "M354",
    price: 3.356,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/images/menu6.png",
    title: "B187",
    price: 4.567,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "8",
    imageSource: "/images/menu12.png",
    title: "J765",
    price: 4.1678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/images/menu11.png",
    title: "B143",
    price: 3.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/images/menu2.png",
    title: "C45T",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "11",
    imageSource: "/images/menu16.png",
    title: "G345",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "12",
    imageSource: "/images/menu15.png",
    title: "C190",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
];

export const fakeMenu = {
  EMPTY,
  SMALL,
  LARGE,
};
